import {Category} from "./category";

export const CATEGORIES: Category[] = [
  {
    code: 'TC',
    name: 'Type of Care',
    serviceCodes: ['DT', 'HH', 'SA']
  },
  {
    code: 'DETOX',
    name: 'Detoxification',
    serviceCodes: ['ADTX', 'BDTX', 'CDTX', 'MDTX', 'ODTX']
  }
];

export const CATEGORY_NAMES: String[] = [
  'Assessment/Pre-treatment', 'Other Addictions',
  'License/Certification/Accreditation',
  'Counseling Services and Education',
  'Special Programs/Groups Offered',
  'Payment Assistance Available',
  'Screening/Testing', 'Detoxification',
  'Age Groups Accepted',
  'Tobacco/Screening Services',
  'Language Services', 'Type of Care', 'Ancillary Services',
  'Other Languages', 'Opioid Medications used in Treatment',
  'Transitional Services', 'Facility Smoking Policy',
  'Service Settings (e.g.', 'Outpatient', 'Residential', 'etc.)',
  'Pharmacotherapies',
  'Payment/Insurance/Funding Accepted',
  'Treatment Approaches', 'Hospitals',
  'American Indian or Alaskan Native Languages',
  'Exclusive Services',
  'Facility Operation (e.g. Private', 'Public)',
  'Gender Accepted',
  'Type of Opioid Treatment'
];

export const CATEGORY_CODES: String[] = [
  'Rational emotive behavioral therapy',
  'Opioids Detoxification',
  'Persons who have experienced intimate partner violence',
  'domestic violence', 'Hospital inpatient',
  'Mental health services', 'Federal or any government funding for substance abuse programs',
  'Methadone',
  'Aftercare/continuing care',
  'French', 'Korean', 'Hmong', 'Smoking not permitted',
  'Assistance with obtaining social services', 'Methadone used in Treatment',
  'Children/adolescents', 'Adult men', 'Interim services for clients',
  'Any Chinese Language', 'Outreach to persons in the community',
  'State financed health insurance plan other than Medicaid', 'Hospital licensing authority',
  'Methamphetamines Detoxification', 'Military families',
  'Employment counseling or training',
  'Other languages(excluding Spanish)',
  'Consumer-run (peer-support) services',
  'Trauma-related counseling', 'Methadone detoxification',
  'Payment assistance (check with facility for details)',
  'Relapse prevention from naltrexone',
  'Non-nicotine smoking/tobacco cessation medications',
  'Early intervention for HIV', 'Navajo',
  'Military insurance (e.g.', 'TRICARE)',
  'Smoking/tobacco cessation counseling',
  'Outpatient day treatment or partial hospitalization',
  'Medicare', 'General Hospital (including VA hospital)',
  'HIV or AIDS education', 'counseling', 'or support',
  'Hepatitis education', 'counseling', 'or support',
  'Spanish', 'HIV testing', 'Yupik',
  'Community reinforcement plus vouchers',
  'Child care for clients children',
  'Substance abuse treatment',
  'Screening for mental health disorders',
  'German', 'Short-term residential',
  'Comprehensive mental health assessment',
  'Do not use medication for opioid addiction',
  'Persons with co-occurring mental and substance abuse disorders',
  'Tribal government', 'No payment accepted',
  'Persons who have experienced trauma',
  'Benzodiazepines Detoxification',
  'Outpatient methadone/buprenorphine or naltrexone',
  'Cognitive/behavioral therapy',
  'Treatment for gambling disorder',
  'Naltrexone used in Treatment',
  'Accepts clients on opioid medication',
  'Veterans', 'Family counseling offered',
  'Hospital inpatient treatment', 'Discharge Planning',
  'Use methadone/buprenorphine for pain management or emergency dosing',
  'Transitional housing or halfway house', 'Health education services other than HIV/AIDS or hepatitis', 'Cash or self-payment', 'Buprenorphine with naloxone  (Suboxone®)', 'Persons who have experienced sexual abuse', 'Female', 'Pregnant/postpartum women', 'Detoxification', 'U.S. Department of Veterans Affairs', 'Buprenorphine detoxification', 'Residential detoxification', 'Disulfiram (Antabuse®)', 'Cocaine Detoxification', 'Individual counseling offered', 'Lesbian', 'gay', 'bisexual', 'or transgender (LGBT) clients', 'Buprenorphine used in Treatment',
  'Methadone maintenance for predetermined time', 'Alcohol Detoxification',
  'Japanese', 'Hindi', 'Buprenorphine maintenance for predetermined time',
  'Hospital inpatient detoxification', 'Marital/couples counseling offered',
  'Long-term residential', 'Native American Indian or Alaska Native languages',
  'Russian', 'Persons with HIV or AIDS', 'Screening for Hepatitis B', 'State department of health',
  '12 - step facilitation approach',
  'Residential beds for clients children', 'Adults', 'Male',
  'TB screening', 'Treatment for internet use disorder',
  'Farsi', 'Computerized treatment',
  'Serve only DWI clients',
  'STD testing',
  'State substance abuse agency',
  'Access to recovery (ATR) voucher',
  'Transportation assistance',
  'IHS/Tribal/Urban (ITU) funds',
  'Portuguese',
  'Young adults',
  'Screening for substance abuse',
  'Acamprosate (Campral®)',
  'Prescribes/administer buprenorphine and/or naltrexone',
  'Case management',
  'National Committee for Quality Assurance',
  'Do not treat opioid addiction',
  'Services for the deaf and hard of hearing',
  'Breath analyzer or blood alcohol testing',
  'Polish',
  'Intensive outpatient treatment',
  'Seniors or older adults',
  'State mental health department',
  'Anger management',
  'Buprenorphine maintenance', 'Adult women', 'Private health insurance',
  'Ojibwa', 'All Clients in Opioid Treatment Program',
  'Arabic', 'Regular outpatient treatment',
  'Council on Accreditation', 'Italian', 'Adolescents', 'Tagalog',
  'The Joint Commission, Comprehensive substance abuse assessment',
  'Sliding fee scale (fee is based on income and other factors)',
  'Group counseling offered', 'Dialectical behavioral therapy',
  'Extended-release', 'injectible Naltrexone (Vivitrol®)',
  'Relapse prevention', 'Hopi',
  'Contingency management/motivational incentive',
  'Motivational interviewing', 'Active duty military', 'Greek', 'State government',
  'Domestic violence services-family or partner', 'DUI/DWI clients',
  'Martix Model', 'Self-help groups', 'Smoking permitted without restriction',
  'Treatment for non-substance abuse addiction disorder', 'Department of Defense',
  'Residential', 'Substance abuse education', 'Acupuncture',
  'Buprenorphine sub-dermal implant (Probuphine®)', 'Hebrew',
  'SAMHSA-certified Opioid Treatment Program', 'Outpatient detoxification',
  'Transitional age young adults', 'Private organization',
  'Methadone and buprenorphine clients only', 'Smoking permitted in designated area',
  'Screening for Hepatitis C', 'Indian Health Service', 'Substance abuse counseling approach',
  'Vietnamese', 'Lakota', 'Local', 'county', 'or community government', 'Medicaid',
  'Healthcare Facilities Accreditation Program',
  'Drug or alcohol urine screening', 'Naltrexone (oral)', 'Methadone clients only',
  'Medications for psychiatric disorders', 'Brief intervention approach', 'Housing services',
  'Screening for tobacco use', 'Buprenorphine without naloxone', 'Creole', 'Outpatient',
  'Commission on Accreditation of Rehabilitation Facilities', 'Psychiatric hospital',
  'Methadone maintenance', 'Clients referred from the court/judicial system',
  'Social skills development', 'Nicotine replacement therapy'
];
