import {TreatmentFacility} from './treatment-facility';
import {GeoPoint} from './geo-point';

export const TREATMENT_FACILITIES: TreatmentFacility[] = [

  {
    id: 1,
    formatted_address: '1 Test St, Test City, MD 21851, USA',
    name1: 'Test Treatment Facility 1',
    city: '',
    google_location: '',
    google_place_id: '',
    host: '',
    intake1: '',
    intake2: '',
    intake_prompt: '',
    last_update: '',
    name2: '',
    path: '',
    phone: '',
    street1: '',
    street2: '',
    type_facility: '',
    website: '',
    zip: '',
    zip4: '',
    service_names: [],
    service_codes: ['FCO', 'STDT', 'TWFA', 'HIT', 'SA', 'ODT', 'CMHA', 'F31',
      'N13', 'DUO', 'MN', 'NU', 'ADD', 'SHC', 'EIH', 'BDTX', 'ADTX',
      'GL', 'RS', 'VAMC', 'F92', 'HV', 'SAE', 'VTRL', 'NMOA',
      'CBT', 'CCC', 'RELP', 'SMPD', 'RES', 'MCO', 'PW',
      'MXM', 'AH', 'F17', 'PA', 'SP', 'MPD',
      'N23', 'TRC', 'GH', 'MDTX', 'HFAP',
      'SSA', 'SHB', 'F37', 'MALE', 'BIA',
      'RD', 'CM', 'BMO', 'F30', 'OD', 'COA', 'F67',
      'CRV', 'F4', 'STG', 'ADLT', 'CDTX', 'STMH', 'MU', 'DDF', 'TBG', 'BC',
      'HS', 'OMB', 'TRMA', 'TCC', 'JC', 'DAUT', 'OP', 'MOA', 'YAD', 'BWN',
      'F43', 'DBT', 'NRT', 'DVFP', 'MM', 'F70', 'REBT', 'DB', 'HEOH', 'CSAA',
      'BSDM', 'MO', 'TID', 'OTPA', 'LCCG', 'PEER', 'SS', 'F81', 'ODTX', 'MD',
      'AOSS', 'DP', 'F19', 'CJ', 'TGD', 'STAG', 'WN', 'EMP', 'SACA', 'DT',
      'FSA', 'NXN', 'PI', 'F42', 'CO', 'HAEC', 'OTP', 'SMOP', 'ITU',
      'HH', 'SMHD', 'FX', 'TAY', 'ISC', 'OIT', 'STDH', 'SI', 'F28',
      'UBN', 'ACM', 'TBS', 'MI', 'CARF', 'HIVT', 'N18', 'AD', 'TA',
      'ANG', 'IH', 'ATR', 'SE', 'BUM', 'DM', 'ACU', 'HID',
      'BMW', 'CHLD', 'XA', 'NSC', 'N24', 'ACC', 'ADM', 'SHG',
      'STU', 'CT', 'F25', 'NCQA', 'BU', 'PSYH', 'PVT', 'DV', 'CMI', 'SSD',
      'BWON', 'DU', 'RL', 'PAIN', 'HI', 'MMW', 'FEM', 'OPC', 'ORT', 'NX', 'SF',
      'METH', 'TAEC', 'GCO', 'NP', 'RPN', 'SMON', 'F66', 'F35', 'BABA', 'VET', 'F36', 'MOTI',
      'F47', 'N40', 'HLA', 'NOOP', 'MHS', 'DSF', 'ICO', 'MF', 'MC'],
    category_names: ['Assessment/Pre-treatment', 'Other Addictions',
      'License/Certification/Accreditation',
      'Counseling Services and Education',
      'Special Programs/Groups Offered',
      'Payment Assistance Available',
      'Screening/Testing', 'Detoxification',
      'Age Groups Accepted',
      'Tobacco/Screening Services',
      'Language Services', 'Type of Care', 'Ancillary Services',
      'Other Languages', 'Opioid Medications used in Treatment',
      'Transitional Services', 'Facility Smoking Policy',
      'Service Settings (e.g.', 'Outpatient', 'Residential', 'etc.)',
      'Pharmacotherapies',
      'Payment/Insurance/Funding Accepted',
      'Treatment Approaches', 'Hospitals',
      'American Indian or Alaskan Native Languages',
      'Exclusive Services',
      'Facility Operation (e.g. Private', 'Public)',
      'Gender Accepted',
      'Type of Opioid Treatment'],
    category_codes: [],
    location: {
      lat: 38.1628711,
      lon: -75.4578135
    },
    latitude: 38.1628711,
    longitude: -75.4578135,
    state: 'MD',
    country: 'USA',
  }
];
